# -*- coding: utf8 -*-
# Copyright 2024 -- 2026 Panobbgo Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from panobbgo.core import Heuristic
from panobbgo.lib import Point
import numpy as np
import uuid
from typing import Any


class DifferentialEvolution(Heuristic):
    """
    Asynchronous Differential Evolution (DE) heuristic.

    It maintains a population of points.
    When a new result arrives, if it corresponds to a trial vector generated by DE,
    it competes with its target vector (parent) for survival in the population.
    The selection criterion uses the strategy's constraint handler, making it
    effective for constrained optimization.

    Parameters:
        CR (float): Crossover probability [0, 1]. Default 0.9.
        F (float): Differential weight [0, 2]. Default 0.8.
        NP (int): Population size. Default 20.
    """

    def __init__(self, strategy, CR=0.9, F=0.8, NP=20):
        super().__init__(strategy, name="DifferentialEvolution")
        self.CR = CR
        self.F = F
        self.NP = NP

        # Population: list of Result objects (or None for uninitialized slots)
        self.population: list[Any] = [None] * NP
        self.pop_size = 0
        self.active_indices = []

        # Pending trials: map ID (str) -> target_index (int)
        self.pending_trials = {}

    def _emit_trial(self, x, target_idx):
        if self._stopped:
            return
        x = self.problem.project(x)
        # Unique id for this trial, drawn from self.rng (not uuid4/OS
        # entropy) so who-tags are seed-reproducible.  Result.who will be
        # "DifferentialEvolution:<uuid>".
        req_id = str(uuid.UUID(bytes=self.rng.bytes(16)))
        self._put(Point(x, f"{self.name}:{req_id}"))
        self.pending_trials[req_id] = target_idx

    def on_start(self):
        # Initial population generation
        # We emit NP random points.
        for i in range(self.NP):
            x = self.problem.random_point(rng=self.rng)
            self._emit_trial(x, i)

    def on_new_results(self, results):
        """
        Process new results.
        If result is from our initialization or trial, update population.
        """
        prefix = f"{self.name}:"
        for r in results:
            if not r.who.startswith(prefix):
                continue
            target_idx = self.pending_trials.pop(r.who[len(prefix) :], None)
            if target_idx is None:
                continue

            if self.population[target_idx] is None:
                self.population[target_idx] = r
                self.pop_size += 1
                self.active_indices.append(target_idx)
            elif self.strategy.constraint_handler.is_better(self.population[target_idx], r):
                # Trial (r) is better, replace the target.
                self.population[target_idx] = r

            # Evolution step
            if self.pop_size >= 4:
                # 1. Generate new trial for the current slot
                self._generate_trial(target_idx)

                # 2. Bootstrapping: wake up any idle slot (e.g. slots filled
                # during initialization before pop_size reached 4).  Each
                # slot is visited once, so the snapshot needs no update.
                active_trials = set(self.pending_trials.values())
                for i in range(self.NP):
                    if self.population[i] is not None and i not in active_trials:
                        self._generate_trial(i)

    def on_failed_evaluations(self, points):
        """Free the slots whose trial failed to evaluate, and keep them working.

        A failed trial (the objective crashed) produces no result, so without
        this its slot keeps a pending entry forever and is never woken again.
        A failed initial point is redrawn; a failed trial counts as a lost one
        (the target stays) and the slot gets its next trial.  The same rule
        as :meth:`LSHADE.on_failed_evaluations
        <panobbgo.heuristics.lshade.LSHADE.on_failed_evaluations>`.
        """
        prefix = f"{self.name}:"
        for p in points:
            who = getattr(p, "who", "") or ""
            if not who.startswith(prefix):
                continue
            target_idx = self.pending_trials.pop(who[len(prefix) :], None)
            if target_idx is None:
                continue
            if self.population[target_idx] is None:
                self._emit_trial(self.problem.random_point(rng=self.rng), target_idx)
            else:
                self._generate_trial(target_idx)

    def _generate_trial(self, target_idx):
        """
        Generate a trial vector for the individual at target_idx.
        Mutation: DE/rand/1
        v = r1 + F * (r2 - r3)
        """
        if self.pop_size < 4:
            return

        # Select r1, r2, r3 distinct from target_idx and each other
        # Sample 4 to ensure we can exclude target_idx without re-scanning active_indices
        idxs = [int(i) for i in self.rng.choice(self.active_indices, size=4, replace=False)]
        if target_idx in idxs:
            idxs.remove(target_idx)
            idxs = idxs[:3]
        else:
            idxs = idxs[:3]

        r1, r2, r3 = self.population[idxs[0]], self.population[idxs[1]], self.population[idxs[2]]

        x_r1 = r1.x
        x_r2 = r2.x
        x_r3 = r3.x

        # Mutation
        v = x_r1 + self.F * (x_r2 - x_r3)

        # Crossover
        target_x = self.population[target_idx].x
        dim = self.problem.dim

        cross_points = self.rng.random(dim) < self.CR
        # Ensure at least one parameter changes
        j_rand = int(self.rng.integers(dim))
        cross_points[j_rand] = True

        u = np.where(cross_points, v, target_x)

        # Emit trial
        self._emit_trial(u, target_idx)
