# -*- coding: utf8 -*-
# Copyright 2024 Panobbgo Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from panobbgo.core import Heuristic
from panobbgo.lib import Point
import numpy as np
import uuid
import random


class DifferentialEvolution(Heuristic):
    """
    Asynchronous Differential Evolution (DE) heuristic.

    It maintains a population of points.
    When a new result arrives, if it corresponds to a trial vector generated by DE,
    it competes with its target vector (parent) for survival in the population.
    The selection criterion uses the strategy's constraint handler, making it
    effective for constrained optimization.

    Parameters:
        CR (float): Crossover probability [0, 1]. Default 0.9.
        F (float): Differential weight [0, 2]. Default 0.8.
        NP (int): Population size. Default 20.
    """

    def __init__(self, strategy, CR=0.9, F=0.8, NP=20):
        super().__init__(strategy, name="DifferentialEvolution")
        self.CR = CR
        self.F = F
        self.NP = NP

        # Population: list of Result objects (or None for uninitialized slots)
        self.population = [None] * NP
        self.pop_size = 0
        self.active_indices = []

        # Pending trials: map ID (str) -> target_index (int)
        self.pending_trials = {}

    def _emit_trial(self, x, target_idx):
        if self._stopped:
            return
        try:
            # Project to bounds
            x = self.problem.project(x)

            # Create unique ID for this trial
            req_id = str(uuid.uuid4())
            # Result.who will be "DifferentialEvolution:<uuid>"
            who = f"{self.name}:{req_id}"

            point = Point(x, who)
            self._output.put_nowait(point)

            # Track
            self.pending_trials[req_id] = target_idx

        except Exception as e:
            self.logger.debug(f"Failed to emit DE trial: {e}")

    def on_start(self):
        # Initial population generation
        # We emit NP random points.
        for i in range(self.NP):
            x = self.problem.random_point()
            self._emit_trial(x, i)

    def on_new_results(self, results):
        """
        Process new results.
        If result is from our initialization or trial, update population.
        """
        for r in results:
            # Check if result belongs to us (starts with name:)
            if not r.who.startswith(f"{self.name}:"):
                continue

            try:
                # Parse ID
                parts = r.who.split(":", 1)
                if len(parts) != 2:
                    continue
                req_id = parts[1]

                if req_id in self.pending_trials:
                    target_idx = self.pending_trials.pop(req_id)

                    if self.population[target_idx] is None:
                        self.population[target_idx] = r
                        self.pop_size += 1
                        self.active_indices.append(target_idx)
                    else:
                        target = self.population[target_idx]
                        if self.strategy.constraint_handler.is_better(target, r):
                            # Trial (r) is better, replace target
                            self.population[target_idx] = r
                        # Else keep target

                    # Evolution step
                    if self.pop_size >= 4:
                        # 1. Generate new trial for the current slot
                        self._generate_trial(target_idx)

                        # 2. Bootstrapping: Wake up any idle slots
                        # (e.g. slots filled during initialization before pop_size reached 4)
                        active_trials = set(self.pending_trials.values())
                        # Note: _generate_trial adds to pending_trials immediately if successful

                        for i in range(self.NP):
                            if self.population[i] is not None and i not in active_trials:
                                self._generate_trial(i)
                                # We re-read pending_trials.values() or rely on _generate_trial logic?
                                # _generate_trial might fail if queue full.
                                # But if it succeeds, it adds to pending_trials.
                                # We should update active_trials to avoid redundant calls?
                                # Actually, checking i not in active_trials is enough if we assume single threaded on_new_results.
                                # But we should update the set to reflect the newly added trial.
                                # However, active_trials is a local snapshot.
                                # Re-check:
                                if i in self.pending_trials.values():
                                    active_trials.add(i)  # just in case

            except Exception as e:
                self.logger.debug(f"Error in DE on_new_results: {e}")

    def _generate_trial(self, target_idx):
        """
        Generate a trial vector for the individual at target_idx.
        Mutation: DE/rand/1
        v = r1 + F * (r2 - r3)
        """
        if self.pop_size < 4:
            return

        # Select r1, r2, r3 distinct from target_idx and each other
        # Sample 4 to ensure we can exclude target_idx without re-scanning active_indices
        idxs = random.sample(self.active_indices, 4)
        if target_idx in idxs:
            idxs.remove(target_idx)
            idxs = idxs[:3]
        else:
            idxs = idxs[:3]

        r1, r2, r3 = self.population[idxs[0]], self.population[idxs[1]], self.population[idxs[2]]

        x_r1 = r1.x
        x_r2 = r2.x
        x_r3 = r3.x

        # Mutation
        v = x_r1 + self.F * (x_r2 - x_r3)

        # Crossover
        target_x = self.population[target_idx].x
        dim = self.problem.dim

        cross_points = np.random.rand(dim) < self.CR
        # Ensure at least one parameter changes
        j_rand = np.random.randint(dim)
        cross_points[j_rand] = True

        u = np.where(cross_points, v, target_x)

        # Emit trial
        self._emit_trial(u, target_idx)
